//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserInterface.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm Error.
        /// </summary>
        public static string DashboardCommErrorButton {
            get {
                return ResourceManager.GetString("DashboardCommErrorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls:.
        /// </summary>
        public static string DashboardControlsLabel {
            get {
                return ResourceManager.GetString("DashboardControlsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Times :.
        /// </summary>
        public static string DashboardCycleTimeLabel {
            get {
                return ResourceManager.GetString("DashboardCycleTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIVE.
        /// </summary>
        public static string DashboardHive {
            get {
                return ResourceManager.GetString("DashboardHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Time.
        /// </summary>
        public static string DashboardLeadTime {
            get {
                return ResourceManager.GetString("DashboardLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs :.
        /// </summary>
        public static string DashboardLogLabel {
            get {
                return ResourceManager.GetString("DashboardLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count :.
        /// </summary>
        public static string DashboardMachineLogCountLabel {
            get {
                return ResourceManager.GetString("DashboardMachineLogCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Log.
        /// </summary>
        public static string DashboardMachineLogLabel {
            get {
                return ResourceManager.GetString("DashboardMachineLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK Count :.
        /// </summary>
        public static string DashboardOKCount {
            get {
                return ResourceManager.GetString("DashboardOKCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏸ Pause.
        /// </summary>
        public static string DashboardPauseButton {
            get {
                return ResourceManager.GetString("DashboardPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string DashBoardProductLabel {
            get {
                return ResourceManager.GetString("DashBoardProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string DashboardRepairButtonLabel {
            get {
                return ResourceManager.GetString("DashboardRepairButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔁 Reset.
        /// </summary>
        public static string DashboardResetButton {
            get {
                return ResourceManager.GetString("DashboardResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Start.
        /// </summary>
        public static string DashboardStartButton {
            get {
                return ResourceManager.GetString("DashboardStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Indicators.
        /// </summary>
        public static string DashboardStaticIndicatorsLabel {
            get {
                return ResourceManager.GetString("DashboardStaticIndicatorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏹ Stop.
        /// </summary>
        public static string DashboardStopButton {
            get {
                return ResourceManager.GetString("DashboardStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tossing :.
        /// </summary>
        public static string DashboardTossingLabel {
            get {
                return ResourceManager.GetString("DashboardTossingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count :.
        /// </summary>
        public static string DashboardTotalCountLabel {
            get {
                return ResourceManager.GetString("DashboardTotalCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Animation.
        /// </summary>
        public static string DashboardWorkingAnimationLabel {
            get {
                return ResourceManager.GetString("DashboardWorkingAnimationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Work.
        /// </summary>
        public static string HolderArtWork {
            get {
                return ResourceManager.GetString("HolderArtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string HolderColor {
            get {
                return ResourceManager.GetString("HolderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI.
        /// </summary>
        public static string HolderIMEI {
            get {
                return ResourceManager.GetString("HolderIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPIn.
        /// </summary>
        public static string HolderMPIN {
            get {
                return ResourceManager.GetString("HolderMPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNo.
        /// </summary>
        public static string HolderSerialNumber {
            get {
                return ResourceManager.GetString("HolderSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LoginPage_UserNameLabel {
            get {
                return ResourceManager.GetString("LoginPage_UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Access.
        /// </summary>
        public static string LoginWithUserAccessAccess {
            get {
                return ResourceManager.GetString("LoginWithUserAccessAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LoginWithUserAccessAccessCancelButton {
            get {
                return ResourceManager.GetString("LoginWithUserAccessAccessCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string LoginWithUserAccessAccessCBItemAdministrator {
            get {
                return ResourceManager.GetString("LoginWithUserAccessAccessCBItemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string LoginWithUserAccessAccessCBItemGuest {
            get {
                return ResourceManager.GetString("LoginWithUserAccessAccessCBItemGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string LoginWithUserAccessAccessCBItemTechnicial {
            get {
                return ResourceManager.GetString("LoginWithUserAccessAccessCBItemTechnicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LoginWithUserAccessAccessCBItemUser {
            get {
                return ResourceManager.GetString("LoginWithUserAccessAccessCBItemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginWithUserAccessAccessPassword {
            get {
                return ResourceManager.GetString("LoginWithUserAccessAccessPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string LoginWithUserAccessAccessSubmitButton {
            get {
                return ResourceManager.GetString("LoginWithUserAccessAccessSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string LoginWithUserAccessAccessUserName {
            get {
                return ResourceManager.GetString("LoginWithUserAccessAccessUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string MainViewCommunication {
            get {
                return ResourceManager.GetString("MainViewCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MainViewDashboard {
            get {
                return ResourceManager.GetString("MainViewDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string MainViewData {
            get {
                return ResourceManager.GetString("MainViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EZD mark.
        /// </summary>
        public static string MainViewEZDMark {
            get {
                return ResourceManager.GetString("MainViewEZDMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainViewHome {
            get {
                return ResourceManager.GetString("MainViewHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion.
        /// </summary>
        public static string MainViewMotion {
            get {
                return ResourceManager.GetString("MainViewMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainViewSettings {
            get {
                return ResourceManager.GetString("MainViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASM Software LTd.
        /// </summary>
        public static string MainViewTitle {
            get {
                return ResourceManager.GetString("MainViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetText {
            get {
                return ResourceManager.GetString("ResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet Communication.
        /// </summary>
        public static string SettingsControlsEthernetCommunication {
            get {
                return ResourceManager.GetString("SettingsControlsEthernetCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Commiunication.
        /// </summary>
        public static string SettingsControlsSerialCommunication {
            get {
                return ResourceManager.GetString("SettingsControlsSerialCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate.
        /// </summary>
        public static string SettingsControlsSerialCommunicationBaudRate {
            get {
                return ResourceManager.GetString("SettingsControlsSerialCommunicationBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string SettingsControlsSerialCommunicationConnect {
            get {
                return ResourceManager.GetString("SettingsControlsSerialCommunicationConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        public static string SettingsControlsSerialCommunicationConnectionStatus {
            get {
                return ResourceManager.GetString("SettingsControlsSerialCommunicationConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port Communication.
        /// </summary>
        public static string SettingsControlsSerialPortCommunication {
            get {
                return ResourceManager.GetString("SettingsControlsSerialPortCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port No.
        /// </summary>
        public static string SettingsControlsSerialPortNumber {
            get {
                return ResourceManager.GetString("SettingsControlsSerialPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string SettingsControlsSerialportParity {
            get {
                return ResourceManager.GetString("SettingsControlsSerialportParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP-IP Communication.
        /// </summary>
        public static string SettingsControlsTCPIPCommunication {
            get {
                return ResourceManager.GetString("SettingsControlsTCPIPCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string SettingsControlsTCPIPCommunicationConfiguration {
            get {
                return ResourceManager.GetString("SettingsControlsTCPIPCommunicationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string SettingsControlsTCPIPCommunicationConnect {
            get {
                return ResourceManager.GetString("SettingsControlsTCPIPCommunicationConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string SettingsControlsTCPIPCommunicationIPAddress {
            get {
                return ResourceManager.GetString("SettingsControlsTCPIPCommunicationIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string SettingsControlsTCPIPCommunicationPortNo {
            get {
                return ResourceManager.GetString("SettingsControlsTCPIPCommunicationPortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Communication.
        /// </summary>
        public static string SettingsControlsUSBCommunication {
            get {
                return ResourceManager.GetString("SettingsControlsUSBCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Mode.
        /// </summary>
        public static string SettingViewAutoMode {
            get {
                return ResourceManager.GetString("SettingViewAutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Mode.
        /// </summary>
        public static string SettingViewManualModel {
            get {
                return ResourceManager.GetString("SettingViewManualModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to use ASM Software.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
